# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72116fb631b7f2222317ee5e751f755c3f83fcba483f50ec454f53772c7a9cd0f866e2baa00f5716f4a9f8aa5958dd40b316c22732004819fa7481cd218d6bf6

test:
  secret_key_base: 2a0fb7668c42a7888d606f616adf6f707931292834833843b56842b1e2336f41e5de0e7a1725e5e161b57105838c9e35f80b8001cf6df0a58b7d40bab3313852

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
